name: Release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        default: "0.0.0"
      helm_version:
        description: "Helm version to release"
        required: true
        default: "0.0.0"
      k8s_versions:
        description: "Kubernetes versions this release has been tested on"
        required: true
        default: "x.xx-x.xx"
      release_date:
        description: "Date for this release"
        required: true
        default: "%d %b %Y"

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Branch
        id: branch
        run: |
          version=${{ github.event.inputs.version }}
          version=${version%.*}
          echo "branch=release-$version" >> $GITHUB_OUTPUT

      - name: Checkout Repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          ref: ${{ steps.branch.outputs.branch }}
          token: ${{ secrets.NGINX_PAT }}

      - name: Replace
        run: |
          .github/scripts/release-version-update.sh ${{ github.event.inputs.version }} ${{ github.event.inputs.helm_version }}
          .github/scripts/release-notes-update.sh ${{ github.event.inputs.version }} ${{ github.event.inputs.helm_version }} "${{ github.event.inputs.k8s_versions }}" "${{ github.event.inputs.release_date }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@9153d834b60caba6d51c9b9510b087acf9f33f83 # v6.0.4
        with:
          token: ${{ secrets.NGINX_PAT }}
          commit-message: Release ${{ github.event.inputs.version }}
          title: Release ${{ github.event.inputs.version }}
          branch: docs/release-${{ github.event.inputs.version }}
          author: nginx-bot <integrations@nginx.com>
          body: |
            This automated PR updates the docs for ${{ github.event.inputs.version }} release.
